### ISSUE TITLE
WebApplicationBuilder.Logging.ClearProviders() doesn't clear providers

### ISSUE THREAD

**Issue by halter73** [featherhttp/framework#36]
The `ILoggingBuilder` at `WebApplicationBuilder.Logging` can be used to add `ILoggerProvider`s but not remove them.

**Comment by thenameless314159** [comment]
I believe this might be related to my issue #35, but since this is will be added on .NET 6 I don't think we will get a fix, we should just wait the release scheduled for this summer

**Comment by davidfowl** [comment]
Yep this might be something that needs to change in the host to allow. Or logging will have to be configured with a call back instead of directly on the `WebApplicationBuilder` 😢. Not sure how to fix this one yet.

**Comment by davidfowl** [comment]
I take that back. I found a solution.

**Comment by davidfowl** [comment]
Fixed
