### ISSUE TITLE
"CreateAppHost" task failed unexpectedly on app run 

### ISSUE THREAD

**Issue by LadyNaggaga** [featherhttp/framework#40]
.NET Core SDK Version: 6.0.100-preview.3.21156.2

Steps 

-  Installed the Featherhttp template  
- created a simple FeatherHttp hello world app 
-  Run it - dotnet run
-  Got a build failed error `:\Program Files\dotnet\sdk\6.0.100-preview.3.21156.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(522,5): error MSB4018: The "CreateAppHost" task failed unexpectedly.`

![image](https://user-images.githubusercontent.com/2546640/110331926-b2e10480-7fed-11eb-8378-aa76182c8c42.png)

**Comment by halter73** [comment]
It looks like this is a runtime issue that's been fixed: https://github.com/dotnet/runtime/pull/49341
